"""updating adim location table deleting relation withn area table 

Revision ID: 240f939c89c3
Revises: e3207d66acdf
Create Date: 2025-03-03 22:37:45.909321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '240f939c89c3'
down_revision: Union[str, None] = 'e3207d66acdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('admin_location_area_code_fkey', 'admin_location', type_='foreignkey')
    op.drop_column('admin_location', 'area_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_location', sa.Column('area_code', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('admin_location_area_code_fkey', 'admin_location', 'area', ['area_code'], ['code'])
    # ### end Alembic commands ###
