"""update column name 

Revision ID: 488d50ab3270
Revises: ba1314269fcf
Create Date: 2025-02-25 21:52:24.374039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '488d50ab3270'
down_revision: Union[str, None] = 'ba1314269fcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('invited_bye', sa.String(length=50), nullable=True))
    op.drop_column('user', 'invited_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('invited_by', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('user', 'invited_bye')
    # ### end Alembic commands ###
