"""update admin relation with area

Revision ID: 607081a80c49
Revises: aa035145faa6
Create Date: 2025-02-26 21:27:20.185309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '607081a80c49'
down_revision: Union[str, None] = 'aa035145faa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_location',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('area_code', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.admin_id'], ),
    sa.ForeignKeyConstraint(['area_code'], ['area.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('admin-location')
    op.add_column('admin', sa.Column('area_code', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'admin', 'area', ['area_code'], ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admin', type_='foreignkey')
    op.drop_column('admin', 'area_code')
    op.create_table('admin-location',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('area_code', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.admin_id'], name='admin-location_admin_id_fkey'),
    sa.ForeignKeyConstraint(['area_code'], ['area.code'], name='admin-location_area_code_fkey'),
    sa.PrimaryKeyConstraint('id', name='admin-location_pkey')
    )
    op.drop_table('admin_location')
    # ### end Alembic commands ###
