"""updating area code to have defualt value in admin location  table 

Revision ID: 7f284129da7e
Revises: 240f939c89c3
Create Date: 2025-03-05 21:34:35.782648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f284129da7e'
down_revision: Union[str, None] = '240f939c89c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vip_status',
    sa.Column('vip_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('house_id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['house_id'], ['house.house_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vip_id'),
    sa.UniqueConstraint('house_id')
    )
    op.add_column('admin_location', sa.Column('area_code', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'admin_location', 'area', ['area_code'], ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admin_location', type_='foreignkey')
    op.drop_column('admin_location', 'area_code')
    op.drop_table('vip_status')
    # ### end Alembic commands ###
