"""create all tables

Revision ID: 8fb35793901d
Revises: 
Create Date: 2025-02-26 11:28:24.002497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fb35793901d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('broker',
    sa.Column('broker_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('broker_id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone_no', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('invitation_code', sa.String(length=255), nullable=True),
    sa.Column('invited_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('invitation_code'),
    sa.UniqueConstraint('phone_no')
    )
    op.create_table('admin',
    sa.Column('admin_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone_no', sa.String(length=20), nullable=False),
    sa.Column('id_front', sa.String(length=255), nullable=False),
    sa.Column('id_back', sa.String(length=255), nullable=False),
    sa.Column('area_code', sa.Integer(), nullable=False),
    sa.Column('invitation_code', sa.String(length=255), nullable=True),
    sa.Column('admin_type', sa.Enum('super-admin', 'admin', name='admin_type_enum'), nullable=False),
    sa.ForeignKeyConstraint(['area_code'], ['area.code'], ),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('invitation_code'),
    sa.UniqueConstraint('phone_no')
    )
    op.create_table('house',
    sa.Column('house_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.Enum('sell', 'rent', name='category_enum'), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('condition', sa.Enum('fairly used', 'newly built', 'old and renovated', name='condition_enum'), nullable=True),
    sa.Column('bedroom', sa.Integer(), nullable=False),
    sa.Column('toilets', sa.Integer(), nullable=False),
    sa.Column('listed_by', sa.Enum('agent', 'owner', name='listed_by_enum'), server_default='owner', nullable=True),
    sa.Column('property_type', sa.Enum('apartment', 'condominium', name='property_type_enum'), nullable=False),
    sa.Column('furnish_status', sa.Enum('furnished', 'semi furnished', 'unfurnished', name='furnish_status_enum'), nullable=False),
    sa.Column('bathroom', sa.Integer(), nullable=False),
    sa.Column('facility', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('negotiability', sa.Enum('open to negotiation', 'not', name='negotiability_enum'), nullable=False),
    sa.Column('parking_space', sa.Boolean(), nullable=False),
    sa.Column('assigned_for', sa.Integer(), nullable=False),
    sa.Column('owner', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'available', 'rented', 'sold', name='status_enum'), nullable=False),
    sa.Column('photo', sa.Text(), nullable=True),
    sa.Column('video', sa.String(length=255), nullable=True),
    sa.Column('posted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_for'], ['admin.admin_id'], ),
    sa.ForeignKeyConstraint(['owner'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['posted_by'], ['broker.broker_id'], ),
    sa.PrimaryKeyConstraint('house_id')
    )
    op.create_table('invitation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('request_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('seen', 'not seen', name='invitation_status_enum'), nullable=False),
    sa.Column('visited_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.admin_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('failure_report',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('house_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.admin_id'], ),
    sa.ForeignKeyConstraint(['house_id'], ['house.house_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('success_report',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('house_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('type', sa.Enum('rent', 'sell', name='report_type_enum'), nullable=False),
    sa.Column('commission', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('transaction_photo', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.admin_id'], ),
    sa.ForeignKeyConstraint(['house_id'], ['house.house_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('success_report')
    op.drop_table('failure_report')
    op.drop_table('invitation')
    op.drop_table('house')
    op.drop_table('admin')
    op.drop_table('user')
    op.drop_table('broker')
    op.drop_table('area')
    # ### end Alembic commands ###
