"""updating admin table deleting area code column

Revision ID: a6ead6714741
Revises: 607081a80c49
Create Date: 2025-03-03 21:46:56.504095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6ead6714741'
down_revision: Union[str, None] = '607081a80c49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('admin_area_code_fkey', 'admin', type_='foreignkey')
    op.drop_column('admin', 'area_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('area_code', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('admin_area_code_fkey', 'admin', 'area', ['area_code'], ['code'])
    # ### end Alembic commands ###
