"""adding table admin location

Revision ID: aa035145faa6
Revises: 8fb35793901d
Create Date: 2025-02-26 20:39:33.682841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa035145faa6'
down_revision: Union[str, None] = '8fb35793901d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin-location',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('area_code', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.admin_id'], ),
    sa.ForeignKeyConstraint(['area_code'], ['area.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('admin_area_code_fkey', 'admin', type_='foreignkey')
    op.drop_column('admin', 'area_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('area_code', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('admin_area_code_fkey', 'admin', 'area', ['area_code'], ['code'])
    op.drop_table('admin-location')
    # ### end Alembic commands ###
