"""updating admin table deleting area and admin forign relation column

Revision ID: e3207d66acdf
Revises: a6ead6714741
Create Date: 2025-03-03 21:54:04.753746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3207d66acdf'
down_revision: Union[str, None] = 'a6ead6714741'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
